name: dgca-verifier-app-android

trigger:
- none

resources:
  repositories:
  - repository: dgca-app-core-android
    type: github
    name: eu-digital-green-certificates/dgca-app-core-android
    ref: 'refs/tags/1.0.0'
    endpoint: 'GitHub - it-eucert-team'

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs:
  - job: Build_apk
    steps:
    - checkout: self
      clean: true
    - checkout: dgca-app-core-android
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQube Azure 8.9'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(System.TeamProject)_it-dgc-verifier-service'
        cliProjectName: '$(System.TeamProject)_it-dgc-verifier-service'
        cliProjectVersion: '$(Build.SourceVersion)'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.java.binaries=.
          sonar.exclusions=**/CCReport*/**
          sonar.branch.name=master

    - task: SonarQubeAnalyze@4

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
        
    - task: UpdateAndroidVersionGradle@1
      inputs:
        buildGradlePath: 'dgca-verifier-app-android/buildSrc/src/main/java/AppConfig.kt'
        versionCode: '$(Build.BuildId)'
        versionName: '1.0.0'

    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'dgca-verifier-app-android/gradlew'
        workingDirectory: 'dgca-verifier-app-android'
        tasks: 'build'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: AndroidSigning@3
      inputs:
        apkFiles: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/apk/release/app-release-unsigned.apk'
        apksignerKeystoreFile: 'android-c19-key.jks'
        apksignerKeystorePassword: '$(keystorepassword)'
        apksignerKeystoreAlias: '$(keystorealias)'
        apksignerKeyPassword: '$(keystorepassword)'
        zipalign: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/apk/release/app-release-unsigned.apk'
        artifact: 'apk'
        publishLocation: 'pipeline'
    
    - task: AppCenterDistribute@3
      inputs:
          serverEndpoint: 'DGC-App'
          appSlug: 'sogei/dgca-verifier-app-android'
          appFile: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/apk/release/app-release-unsigned.apk'
          symbolsOption: 'Android'
          releaseNotesOption: 'input'
          releaseNotesInput: 'Prova'
          destinationType: 'groups'
          isSilent: true

    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'dgca-verifier-app-android/gradlew'
        workingDirectory: 'dgca-verifier-app-android'
        tasks: ':app:bundleRelease'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

    - task: CopyFiles@2
      inputs:
        contents: '**/*.aab'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: AndroidSigning@2
      inputs:
        apkFiles: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.aab'
        jarsignerKeystoreFile: 'android-c19-key.jks'
        jarsignerKeystorePassword: '$(keystorepassword)'
        jarsignerKeystoreAlias: '$(keystorealias)'
        jarsignerKeyPassword: '$(keystorepassword)'
        jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.aab'
        artifact: 'bundle'
        publishLocation: 'pipeline'
    
    - task: GooglePlayReleaseBundle@3
      inputs:
        serviceConnection: 'verificac19-google-play'
        applicationId: 'it.ministerodellasalute.verificaC19'
        bundleFile: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.aab'
        track: 'internal'
        languageCode: 'en-GB'


# - stage: DistributeToAppcenter
#   jobs:
#   - job: ApkToAppCenter
#     steps:
#     - task: DownloadPipelineArtifact@2
#       inputs:
#         buildType: 'current'
#         artifactName: 'artifact'
#         targetPath: '$(Pipeline.Workspace)'
#     - task: AppCenterDistribute@3
#       inputs:
#         serverEndpoint: 'DGC-App'
#         appSlug: 'sogei/dgca-verifier-app-android'
#         appFile: '$(Pipeline.Workspace)/dgca-verifier-app-android/app/build/outputs/apk/release/app-release-unsigned.apk'
#         releaseNotesOption: 'input'
#         releaseNotesInput: 'Prova'
#         destinationType: 'groups'

# - stage: DistributeToGoogleStore
#   jobs:
#   - job: ReleaseToGooglePlay
#     steps:
#     - task: DownloadPipelineArtifact@2
#       inputs:
#         buildType: 'current'
#         artifactName: 'artifact'
#         targetPath: '$(Pipeline.Workspace)'
  
#     - task: GooglePlayReleaseBundle@3
#       inputs:
#         serviceConnection: 'verificac19-google-play'
#         applicationId: 'it.ministerodellasalute.verificaC19'
#         bundleFile: '$(Pipeline.Workspace)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.aab'
#         track: 'internal'
#         languageCode: 'en-GB'
