name: dgca-verifier-app-android

trigger:
- none

resources:
  repositories:
  - repository: dgca-app-core-android
    type: github
    name: eu-digital-green-certificates/dgca-app-core-android
    ref: 'refs/tags/1.0.0'
    endpoint: 'GitHub - it-eucert-team'

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  clean: true
- checkout: dgca-app-core-android
- script: |
    ls -l

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'dgca-verifier-app-android/gradlew'
    workingDirectory: 'dgca-verifier-app-android'
    #tasks: ':app:bundleRelease'
    tasks: 'Release'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

# - task: CopyFiles@2
#   inputs:
#     contents: '**/*.aab'
#     targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'test.jks'
    apksignerKeystorePassword: '$(keystorepassword)'
    apksignerKeystoreAlias: '$(keystorealias)'
    apksignerKeyPassword: '$(keystorepassword)'
    zipalign: false

# - task: AndroidSigning@2
#   inputs:
#     apkFiles: '**/*.aab'
#     jarsignerKeystoreFile: 'test.jks'
#     jarsignerKeystorePassword: '$(keystorepassword)'
#     jarsignerKeystoreAlias: 'test'
#     jarsignerKeyPassword: '$(keystorepassword)'
#     # The two Arguments working there magic:
#     jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
#     zipalign: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'outputs'
    artifactType: 'container'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'DGC-App'
    appSlug: 'sogei/dgca-verifier-app-android'
    #appFile: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.aab'
    appFile: '$(build.artifactStagingDirectory)/dgca-verifier-app-android/app/build/outputs/bundle/release/app-release.apk'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Prova'
    destinationType: 'groups'